# -*- coding: utf-8 -*-
"""Assignment week_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tInnKaPjTwFcAmQ_v4tQyBmIvGrmCAvi
"""

import pandas as pd

# Load data from a CSV file
data = pd.read_excel('/content/sample_data/Assignment 3 Data sample.xlsx')

# Display the first few rows of the dataframe
print("First few rows of the dataframe:")
print(data.head())

# Perform basic data analysis
print("\nData analysis:")
print("Number of rows:", len(data))
print("Summary statistics:")
print(data.describe())

# Data cleaning: Drop rows with missing values
cleaned_data = data.dropna()

# Perform additional analysis after cleaning
print("\nAfter cleaning:")
print("Number of rows after cleaning:", len(cleaned_data))
print("Summary statistics after cleaning:")
print(cleaned_data.describe())